server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/devmodTaller
    username: postgres
    password: admin
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
